package com.chen.fy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFyAdvisoryCost<M extends BaseFyAdvisoryCost<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setAdvisoryOrg(java.lang.String advisoryOrg) {
		set("advisory_org", advisoryOrg);
	}
	
	public java.lang.String getAdvisoryOrg() {
		return getStr("advisory_org");
	}

	public void setAdvisoryPersion(java.lang.String advisoryPersion) {
		set("advisory_persion", advisoryPersion);
	}
	
	public java.lang.String getAdvisoryPersion() {
		return getStr("advisory_persion");
	}

	public void setAdvisoryDate(java.util.Date advisoryDate) {
		set("advisory_date", advisoryDate);
	}
	
	public java.util.Date getAdvisoryDate() {
		return get("advisory_date");
	}

	public void setAnswerPersion(java.lang.Integer answerPersion) {
		set("answer_persion", answerPersion);
	}
	
	public java.lang.Integer getAnswerPersion() {
		return getInt("answer_persion");
	}

	public void setAnswerDate(java.util.Date answerDate) {
		set("answer_date", answerDate);
	}
	
	public java.util.Date getAnswerDate() {
		return get("answer_date");
	}

	public void setCommodityName(java.lang.String commodityName) {
		set("commodity_name", commodityName);
	}
	
	public java.lang.String getCommodityName() {
		return getStr("commodity_name");
	}

	public void setCommoditySpec(java.lang.String commoditySpec) {
		set("commodity_spec", commoditySpec);
	}
	
	public java.lang.String getCommoditySpec() {
		return getStr("commodity_spec");
	}

	public void setMapNo(java.lang.String mapNo) {
		set("map_no", mapNo);
	}
	
	public java.lang.String getMapNo() {
		return getStr("map_no");
	}

	public void setUnit(java.lang.Integer unit) {
		set("unit", unit);
	}
	
	public java.lang.Integer getUnit() {
		return getInt("unit");
	}

	public void setBaseCost(java.math.BigDecimal baseCost) {
		set("base_cost", baseCost);
	}
	
	public java.math.BigDecimal getBaseCost() {
		return get("base_cost");
	}

	public void setCustomerProfitCost(java.math.BigDecimal customerProfitCost) {
		set("customer_profit_cost", customerProfitCost);
	}
	
	public java.math.BigDecimal getCustomerProfitCost() {
		return get("customer_profit_cost");
	}

	public void setCustomerProfitAmount(java.math.BigDecimal customerProfitAmount) {
		set("customer_profit_amount", customerProfitAmount);
	}
	
	public java.math.BigDecimal getCustomerProfitAmount() {
		return get("customer_profit_amount");
	}

	public void setQuantity(java.math.BigDecimal quantity) {
		set("quantity", quantity);
	}
	
	public java.math.BigDecimal getQuantity() {
		return get("quantity");
	}

}
