package com.chen.fy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFyBusinessProduce<M extends BaseFyBusinessProduce<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setCategoryId(java.lang.Integer categoryId) {
		set("category_id", categoryId);
	}
	
	public java.lang.Integer getCategoryId() {
		return getInt("category_id");
	}

	public void setPlanerId(java.lang.Integer planerId) {
		set("planer_id", planerId);
	}
	
	public java.lang.Integer getPlanerId() {
		return getInt("planer_id");
	}

	public void setExecuStatus(java.lang.String execuStatus) {
		set("execu_status", execuStatus);
	}
	
	public java.lang.String getExecuStatus() {
		return getStr("execu_status");
	}

	public void setUrgentStatus(java.lang.String urgentStatus) {
		set("urgent_status", urgentStatus);
	}
	
	public java.lang.String getUrgentStatus() {
		return getStr("urgent_status");
	}

	public void setOrderDate(java.util.Date orderDate) {
		set("order_date", orderDate);
	}
	
	public java.util.Date getOrderDate() {
		return get("order_date");
	}

	public void setDeliveryDate(java.util.Date deliveryDate) {
		set("delivery_date", deliveryDate);
	}
	
	public java.util.Date getDeliveryDate() {
		return get("delivery_date");
	}

	public void setWorkOrderNo(java.lang.String workOrderNo) {
		set("work_order_no", workOrderNo);
	}
	
	public java.lang.String getWorkOrderNo() {
		return getStr("work_order_no");
	}

	public void setDeliveryNo(java.lang.String deliveryNo) {
		set("delivery_no", deliveryNo);
	}
	
	public java.lang.String getDeliveryNo() {
		return getStr("delivery_no");
	}

	public void setCommodityName(java.lang.String commodityName) {
		set("commodity_name", commodityName);
	}
	
	public java.lang.String getCommodityName() {
		return getStr("commodity_name");
	}

	public void setCommoditySpec(java.lang.String commoditySpec) {
		set("commodity_spec", commoditySpec);
	}
	
	public java.lang.String getCommoditySpec() {
		return getStr("commodity_spec");
	}

	public void setMapNo(java.lang.Integer mapNo) {
		set("map_no", mapNo);
	}
	
	public java.lang.Integer getMapNo() {
		return getInt("map_no");
	}

	public void setTechnology(java.lang.String technology) {
		set("technology", technology);
	}
	
	public java.lang.String getTechnology() {
		return getStr("technology");
	}

	public void setMachiningRequire(java.lang.String machiningRequire) {
		set("machining_require", machiningRequire);
	}
	
	public java.lang.String getMachiningRequire() {
		return getStr("machining_require");
	}

	public void setQuantity(java.lang.Integer quantity) {
		set("quantity", quantity);
	}
	
	public java.lang.Integer getQuantity() {
		return getInt("quantity");
	}

	public void setUnit(java.lang.Integer unit) {
		set("unit", unit);
	}
	
	public java.lang.Integer getUnit() {
		return getInt("unit");
	}

	public void setIsCreatePlan(java.lang.Boolean isCreatePlan) {
		set("is_create_plan", isCreatePlan);
	}
	
	public java.lang.Boolean getIsCreatePlan() {
		return get("is_create_plan");
	}

	public void setDistributeTime(java.util.Date distributeTime) {
		set("distribute_time", distributeTime);
	}
	
	public java.util.Date getDistributeTime() {
		return get("distribute_time");
	}

	public void setHandleStatus(java.lang.String handleStatus) {
		set("handle_status", handleStatus);
	}
	
	public java.lang.String getHandleStatus() {
		return getStr("handle_status");
	}

	public void setPlanTime(java.util.Date planTime) {
		set("plan_time", planTime);
	}
	
	public java.util.Date getPlanTime() {
		return get("plan_time");
	}

	public void setPlanFinshTime(java.util.Date planFinshTime) {
		set("plan_finsh_time", planFinshTime);
	}
	
	public java.util.Date getPlanFinshTime() {
		return get("plan_finsh_time");
	}

	public void setPlanRemark(java.lang.String planRemark) {
		set("plan_remark", planRemark);
	}
	
	public java.lang.String getPlanRemark() {
		return getStr("plan_remark");
	}

	public void setInWarehouseTime(java.util.Date inWarehouseTime) {
		set("in_warehouse_time", inWarehouseTime);
	}
	
	public java.util.Date getInWarehouseTime() {
		return get("in_warehouse_time");
	}

}
