package com.chen.fy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFyPurchaseAudit<M extends BaseFyPurchaseAudit<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	public void setPurchaseCost(java.math.BigDecimal purchaseCost) {
		set("purchase_cost", purchaseCost);
	}
	
	public java.math.BigDecimal getPurchaseCost() {
		return get("purchase_cost");
	}

	public void setPurchaseAccount(java.math.BigDecimal purchaseAccount) {
		set("purchase_account", purchaseAccount);
	}
	
	public java.math.BigDecimal getPurchaseAccount() {
		return get("purchase_account");
	}

	public void setSupplierId(java.lang.Integer supplierId) {
		set("supplier_id", supplierId);
	}
	
	public java.lang.Integer getSupplierId() {
		return getInt("supplier_id");
	}

	public void setDiscount(java.math.BigDecimal discount) {
		set("discount", discount);
	}
	
	public java.math.BigDecimal getDiscount() {
		return get("discount");
	}

	public void setDiscountAccount(java.math.BigDecimal discountAccount) {
		set("discount_account", discountAccount);
	}
	
	public java.math.BigDecimal getDiscountAccount() {
		return get("discount_account");
	}

	public void setAuditStatus(java.lang.String auditStatus) {
		set("audit_status", auditStatus);
	}
	
	public java.lang.String getAuditStatus() {
		return getStr("audit_status");
	}

	public void setAuditBy(java.lang.Integer auditBy) {
		set("audit_by", auditBy);
	}
	
	public java.lang.Integer getAuditBy() {
		return getInt("audit_by");
	}

	public void setAuditTime(java.util.Date auditTime) {
		set("audit_time", auditTime);
	}
	
	public java.util.Date getAuditTime() {
		return get("audit_time");
	}

}
