package com.chen.fy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFyBusinessWarehouse<M extends BaseFyBusinessWarehouse<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setCategoryId(java.lang.Integer categoryId) {
		set("category_id", categoryId);
	}
	
	public java.lang.Integer getCategoryId() {
		return getInt("category_id");
	}

	public void setPlanerId(java.lang.Integer planerId) {
		set("planer_id", planerId);
	}
	
	public java.lang.Integer getPlanerId() {
		return getInt("planer_id");
	}

	public void setExecuStatus(java.lang.String execuStatus) {
		set("execu_status", execuStatus);
	}
	
	public java.lang.String getExecuStatus() {
		return getStr("execu_status");
	}

	public void setUrgentStatus(java.lang.String urgentStatus) {
		set("urgent_status", urgentStatus);
	}
	
	public java.lang.String getUrgentStatus() {
		return getStr("urgent_status");
	}

	public void setBillDate(java.util.Date billDate) {
		set("bill_date", billDate);
	}
	
	public java.util.Date getBillDate() {
		return get("bill_date");
	}

	public void setDeliveryDate(java.util.Date deliveryDate) {
		set("delivery_date", deliveryDate);
	}
	
	public java.util.Date getDeliveryDate() {
		return get("delivery_date");
	}

	public void setWorkBillNo(java.lang.String workBillNo) {
		set("work_bill_no", workBillNo);
	}
	
	public java.lang.String getWorkBillNo() {
		return getStr("work_bill_no");
	}

	public void setDeliveryNo(java.lang.String deliveryNo) {
		set("delivery_no", deliveryNo);
	}
	
	public java.lang.String getDeliveryNo() {
		return getStr("delivery_no");
	}

	public void setCommodityName(java.lang.String commodityName) {
		set("commodity_name", commodityName);
	}
	
	public java.lang.String getCommodityName() {
		return getStr("commodity_name");
	}

	public void setCommoditySpec(java.lang.String commoditySpec) {
		set("commodity_spec", commoditySpec);
	}
	
	public java.lang.String getCommoditySpec() {
		return getStr("commodity_spec");
	}

	public void setMapNo(java.lang.Integer mapNo) {
		set("map_no", mapNo);
	}
	
	public java.lang.Integer getMapNo() {
		return getInt("map_no");
	}

	public void setTechnology(java.lang.String technology) {
		set("technology", technology);
	}
	
	public java.lang.String getTechnology() {
		return getStr("technology");
	}

	public void setMachiningRequire(java.lang.String machiningRequire) {
		set("machining_require", machiningRequire);
	}
	
	public java.lang.String getMachiningRequire() {
		return getStr("machining_require");
	}

	public void setQuantity(java.lang.Integer quantity) {
		set("quantity", quantity);
	}
	
	public java.lang.Integer getQuantity() {
		return getInt("quantity");
	}

	public void setUnit(java.lang.Integer unit) {
		set("unit", unit);
	}
	
	public java.lang.Integer getUnit() {
		return getInt("unit");
	}

	public void setInTime(java.util.Date inTime) {
		set("in_time", inTime);
	}
	
	public java.util.Date getInTime() {
		return get("in_time");
	}

	public void setRealInQuantity(java.lang.Integer realInQuantity) {
		set("real_in_quantity", realInQuantity);
	}
	
	public java.lang.Integer getRealInQuantity() {
		return getInt("real_in_quantity");
	}

	public void setInFrom(java.lang.String inFrom) {
		set("in_from", inFrom);
	}
	
	public java.lang.String getInFrom() {
		return getStr("in_from");
	}

	public void setIsCreateCheck(java.lang.Boolean isCreateCheck) {
		set("is_create_check", isCreateCheck);
	}
	
	public java.lang.Boolean getIsCreateCheck() {
		return get("is_create_check");
	}

	public void setCheckCreateTime(java.util.Date checkCreateTime) {
		set("check_create_time", checkCreateTime);
	}
	
	public java.util.Date getCheckCreateTime() {
		return get("check_create_time");
	}

	public void setCheckTime(java.util.Date checkTime) {
		set("check_time", checkTime);
	}
	
	public java.util.Date getCheckTime() {
		return get("check_time");
	}

	public void setCheckQuantity(java.lang.Integer checkQuantity) {
		set("check_quantity", checkQuantity);
	}
	
	public java.lang.Integer getCheckQuantity() {
		return getInt("check_quantity");
	}

	public void setCheckResult(java.lang.String checkResult) {
		set("check_result", checkResult);
	}
	
	public java.lang.String getCheckResult() {
		return getStr("check_result");
	}

	public void setCheckHandle(java.lang.String checkHandle) {
		set("check_handle", checkHandle);
	}
	
	public java.lang.String getCheckHandle() {
		return getStr("check_handle");
	}

	public void setIsCreateQuality(java.lang.Boolean isCreateQuality) {
		set("is_create_quality", isCreateQuality);
	}
	
	public java.lang.Boolean getIsCreateQuality() {
		return get("is_create_quality");
	}

	public void setIsCreateCanOut(java.lang.Boolean isCreateCanOut) {
		set("is_create_can_out", isCreateCanOut);
	}
	
	public java.lang.Boolean getIsCreateCanOut() {
		return get("is_create_can_out");
	}

	public void setCreateOutTime(java.util.Date createOutTime) {
		set("create_out_time", createOutTime);
	}
	
	public java.util.Date getCreateOutTime() {
		return get("create_out_time");
	}

	public void setIsCreatePay(java.lang.Boolean isCreatePay) {
		set("is_create_pay", isCreatePay);
	}
	
	public java.lang.Boolean getIsCreatePay() {
		return get("is_create_pay");
	}

	public void setPayCreateTime(java.util.Date payCreateTime) {
		set("pay_create_time", payCreateTime);
	}
	
	public java.util.Date getPayCreateTime() {
		return get("pay_create_time");
	}

}
