package com.chen.fy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFyBusinessPurchaseCallback<M extends BaseFyBusinessPurchaseCallback<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setPurchaseNo(java.lang.String purchaseNo) {
		set("purchase_no", purchaseNo);
	}
	
	public java.lang.String getPurchaseNo() {
		return getStr("purchase_no");
	}

	public void setPurchaseDate(java.util.Date purchaseDate) {
		set("purchase_date", purchaseDate);
	}
	
	public java.util.Date getPurchaseDate() {
		return get("purchase_date");
	}

	public void setPurchaseSingleWeight(java.math.BigDecimal purchaseSingleWeight) {
		set("purchase_single_weight", purchaseSingleWeight);
	}
	
	public java.math.BigDecimal getPurchaseSingleWeight() {
		return get("purchase_single_weight");
	}

	public void setPurchaseWeight(java.math.BigDecimal purchaseWeight) {
		set("purchase_weight", purchaseWeight);
	}
	
	public java.math.BigDecimal getPurchaseWeight() {
		return get("purchase_weight");
	}

	public void setPurchaseCost(java.math.BigDecimal purchaseCost) {
		set("purchase_cost", purchaseCost);
	}
	
	public java.math.BigDecimal getPurchaseCost() {
		return get("purchase_cost");
	}

	public void setPurchaseAccount(java.math.BigDecimal purchaseAccount) {
		set("purchase_account", purchaseAccount);
	}
	
	public java.math.BigDecimal getPurchaseAccount() {
		return get("purchase_account");
	}

	public void setParentId(java.lang.Integer parentId) {
		set("parent_id", parentId);
	}
	
	public java.lang.Integer getParentId() {
		return getInt("parent_id");
	}

	public void setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	public void setSupplierId(java.lang.Integer supplierId) {
		set("supplier_id", supplierId);
	}
	
	public java.lang.Integer getSupplierId() {
		return getInt("supplier_id");
	}

	public void setPurchaseRemark(java.lang.String purchaseRemark) {
		set("purchase_remark", purchaseRemark);
	}
	
	public java.lang.String getPurchaseRemark() {
		return getStr("purchase_remark");
	}

	public void setIsDownload(java.lang.Boolean isDownload) {
		set("is_download", isDownload);
	}
	
	public java.lang.Boolean getIsDownload() {
		return get("is_download");
	}

	public void setHangStatus(java.lang.String hangStatus) {
		set("hang_status", hangStatus);
	}
	
	public java.lang.String getHangStatus() {
		return getStr("hang_status");
	}

	public void setUnhangQuantity(java.lang.Integer unhangQuantity) {
		set("unhang_quantity", unhangQuantity);
	}
	
	public java.lang.Integer getUnhangQuantity() {
		return getInt("unhang_quantity");
	}

	public void setHangQuantity(java.lang.Integer hangQuantity) {
		set("hang_quantity", hangQuantity);
	}
	
	public java.lang.Integer getHangQuantity() {
		return getInt("hang_quantity");
	}

	public void setPurchaseQuantity(java.lang.Integer purchaseQuantity) {
		set("purchase_quantity", purchaseQuantity);
	}
	
	public java.lang.Integer getPurchaseQuantity() {
		return getInt("purchase_quantity");
	}

	public void setPurchaseTitle(java.lang.String purchaseTitle) {
		set("purchase_title", purchaseTitle);
	}
	
	public java.lang.String getPurchaseTitle() {
		return getStr("purchase_title");
	}

	public void setPurchaseDeliveryDate(java.util.Date purchaseDeliveryDate) {
		set("purchase_delivery_date", purchaseDeliveryDate);
	}
	
	public java.util.Date getPurchaseDeliveryDate() {
		return get("purchase_delivery_date");
	}

	public void setAuditStatus(java.lang.String auditStatus) {
		set("audit_status", auditStatus);
	}
	
	public java.lang.String getAuditStatus() {
		return getStr("audit_status");
	}

	public void setAuditBy(java.lang.Integer auditBy) {
		set("audit_by", auditBy);
	}
	
	public java.lang.Integer getAuditBy() {
		return getInt("audit_by");
	}

	public void setAuditTime(java.util.Date auditTime) {
		set("audit_time", auditTime);
	}
	
	public java.util.Date getAuditTime() {
		return get("audit_time");
	}

	public void setWorkOrderNo(java.lang.String workOrderNo) {
		set("work_order_no", workOrderNo);
	}
	
	public java.lang.String getWorkOrderNo() {
		return getStr("work_order_no");
	}

	public void setSupplierNo(java.lang.String supplierNo) {
		set("supplier_no", supplierNo);
	}
	
	public java.lang.String getSupplierNo() {
		return getStr("supplier_no");
	}

	public void setAddStatus(java.lang.Integer addStatus) {
		set("add_status", addStatus);
	}
	
	public java.lang.Integer getAddStatus() {
		return getInt("add_status");
	}

	public void setIsHasTax(java.lang.String isHasTax) {
		set("is_has_tax", isHasTax);
	}
	
	public java.lang.String getIsHasTax() {
		return getStr("is_has_tax");
	}

}
