package com.chen.fy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFyBusinessOutWarehouse<M extends BaseFyBusinessOutWarehouse<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setReceiveAddress(java.lang.String receiveAddress) {
		set("receive_address", receiveAddress);
	}
	
	public java.lang.String getReceiveAddress() {
		return getStr("receive_address");
	}

	public void setTransportType(java.lang.String transportType) {
		set("transport_type", transportType);
	}
	
	public java.lang.String getTransportType() {
		return getStr("transport_type");
	}

	public void setTransportCompany(java.lang.String transportCompany) {
		set("transport_company", transportCompany);
	}
	
	public java.lang.String getTransportCompany() {
		return getStr("transport_company");
	}

	public void setTransportFee(java.math.BigDecimal transportFee) {
		set("transport_fee", transportFee);
	}
	
	public java.math.BigDecimal getTransportFee() {
		return get("transport_fee");
	}

	public void setTransportWeight(java.lang.Double transportWeight) {
		set("transport_weight", transportWeight);
	}
	
	public java.lang.Double getTransportWeight() {
		return getDouble("transport_weight");
	}

	public void setTransportNo(java.lang.String transportNo) {
		set("transport_no", transportNo);
	}
	
	public java.lang.String getTransportNo() {
		return getStr("transport_no");
	}

	public void setIsCreateGetPay(java.lang.Boolean isCreateGetPay) {
		set("is_create_get_pay", isCreateGetPay);
	}
	
	public java.lang.Boolean getIsCreateGetPay() {
		return get("is_create_get_pay");
	}

	public void setOutTime(java.util.Date outTime) {
		set("out_time", outTime);
	}
	
	public java.util.Date getOutTime() {
		return get("out_time");
	}

	public void setOutQuantity(java.math.BigDecimal outQuantity) {
		set("out_quantity", outQuantity);
	}
	
	public java.math.BigDecimal getOutQuantity() {
		return get("out_quantity");
	}

	public void setIsBackPay(java.lang.Boolean isBackPay) {
		set("is_back_pay", isBackPay);
	}
	
	public java.lang.Boolean getIsBackPay() {
		return get("is_back_pay");
	}

	public void setBackReson(java.lang.String backReson) {
		set("back_reson", backReson);
	}
	
	public java.lang.String getBackReson() {
		return getStr("back_reson");
	}

	public void setIsCreateAfterSale(java.lang.Boolean isCreateAfterSale) {
		set("is_create_after_sale", isCreateAfterSale);
	}
	
	public java.lang.Boolean getIsCreateAfterSale() {
		return get("is_create_after_sale");
	}

	public void setAfterSaleCreateTime(java.util.Date afterSaleCreateTime) {
		set("after_sale_create_time", afterSaleCreateTime);
	}
	
	public java.util.Date getAfterSaleCreateTime() {
		return get("after_sale_create_time");
	}

	public void setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	public void setParentId(java.lang.Integer parentId) {
		set("parent_id", parentId);
	}
	
	public java.lang.Integer getParentId() {
		return getInt("parent_id");
	}

	public void setIsCreateBill(java.lang.Boolean isCreateBill) {
		set("is_create_bill", isCreateBill);
	}
	
	public java.lang.Boolean getIsCreateBill() {
		return get("is_create_bill");
	}

	public void setBillQuantity(java.lang.Integer billQuantity) {
		set("bill_quantity", billQuantity);
	}
	
	public java.lang.Integer getBillQuantity() {
		return getInt("bill_quantity");
	}

	public void setBillCreateTime(java.util.Date billCreateTime) {
		set("bill_create_time", billCreateTime);
	}
	
	public java.util.Date getBillCreateTime() {
		return get("bill_create_time");
	}

	public void setHangTime(java.util.Date hangTime) {
		set("hang_time", hangTime);
	}
	
	public java.util.Date getHangTime() {
		return get("hang_time");
	}

	public void setHangStatus(java.lang.String hangStatus) {
		set("hang_status", hangStatus);
	}
	
	public java.lang.String getHangStatus() {
		return getStr("hang_status");
	}

	public void setHangQuantity(java.math.BigDecimal hangQuantity) {
		set("hang_quantity", hangQuantity);
	}
	
	public java.math.BigDecimal getHangQuantity() {
		return get("hang_quantity");
	}

	public void setHangAmount(java.math.BigDecimal hangAmount) {
		set("hang_amount", hangAmount);
	}
	
	public java.math.BigDecimal getHangAmount() {
		return get("hang_amount");
	}

	public void setUnhangQuantity(java.lang.Integer unhangQuantity) {
		set("unhang_quantity", unhangQuantity);
	}
	
	public java.lang.Integer getUnhangQuantity() {
		return getInt("unhang_quantity");
	}

	public void setIsCreatePaybill(java.lang.Boolean isCreatePaybill) {
		set("is_create_paybill", isCreatePaybill);
	}
	
	public java.lang.Boolean getIsCreatePaybill() {
		return get("is_create_paybill");
	}

	public void setPaybillCreateTime(java.util.Date paybillCreateTime) {
		set("paybill_create_time", paybillCreateTime);
	}
	
	public java.util.Date getPaybillCreateTime() {
		return get("paybill_create_time");
	}

	public void setCreateMonth(java.lang.Integer createMonth) {
		set("create_month", createMonth);
	}
	
	public java.lang.Integer getCreateMonth() {
		return getInt("create_month");
	}

	public void setGetpayMonth(java.lang.Integer getpayMonth) {
		set("getpay_month", getpayMonth);
	}
	
	public java.lang.Integer getGetpayMonth() {
		return getInt("getpay_month");
	}

	public void setCanDownload(java.lang.Boolean canDownload) {
		set("can_download", canDownload);
	}
	
	public java.lang.Boolean getCanDownload() {
		return get("can_download");
	}

	public void setCreateGetpayTime(java.util.Date createGetpayTime) {
		set("create_getpay_time", createGetpayTime);
	}
	
	public java.util.Date getCreateGetpayTime() {
		return get("create_getpay_time");
	}

	public void setTax(java.math.BigDecimal tax) {
		set("tax", tax);
	}
	
	public java.math.BigDecimal getTax() {
		return get("tax");
	}

	public void setUntaxGetpay(java.math.BigDecimal untaxGetpay) {
		set("untax_getpay", untaxGetpay);
	}
	
	public java.math.BigDecimal getUntaxGetpay() {
		return get("untax_getpay");
	}

}
