package com.chen.fy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFyReadyAdd<M extends BaseFyReadyAdd<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setReadyOrderId(java.lang.Integer readyOrderId) {
		set("ready_order_id", readyOrderId);
	}
	
	public java.lang.Integer getReadyOrderId() {
		return getInt("ready_order_id");
	}

	public void setAddOrderId(java.lang.Integer addOrderId) {
		set("add_order_id", addOrderId);
	}
	
	public java.lang.Integer getAddOrderId() {
		return getInt("add_order_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setAddQuantity(java.math.BigDecimal addQuantity) {
		set("add_quantity", addQuantity);
	}
	
	public java.math.BigDecimal getAddQuantity() {
		return get("add_quantity");
	}

}
