package com.chen.fy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePermission<M extends BasePermission<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setKey(java.lang.String key) {
		set("key", key);
	}
	
	public java.lang.String getKey() {
		return getStr("key");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setActionKey(java.lang.String actionKey) {
		set("actionKey", actionKey);
	}
	
	public java.lang.String getActionKey() {
		return getStr("actionKey");
	}

	public void setController(java.lang.String controller) {
		set("controller", controller);
	}
	
	public java.lang.String getController() {
		return getStr("controller");
	}

	public void setPtype(java.lang.Integer ptype) {
		set("ptype", ptype);
	}
	
	public java.lang.Integer getPtype() {
		return getInt("ptype");
	}

	public void setPgroup(java.lang.String pgroup) {
		set("pgroup", pgroup);
	}
	
	public java.lang.String getPgroup() {
		return getStr("pgroup");
	}

}
