package com.chen.fy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFyCheckCollect<M extends BaseFyCheckCollect<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setSupplierId(java.lang.Integer supplierId) {
		set("supplier_id", supplierId);
	}
	
	public java.lang.Integer getSupplierId() {
		return getInt("supplier_id");
	}

	public void setInhouseQuantity(java.math.BigDecimal inhouseQuantity) {
		set("inhouse_quantity", inhouseQuantity);
	}
	
	public java.math.BigDecimal getInhouseQuantity() {
		return get("inhouse_quantity");
	}

	public void setPassQuantity(java.math.BigDecimal passQuantity) {
		set("pass_quantity", passQuantity);
	}
	
	public java.math.BigDecimal getPassQuantity() {
		return get("pass_quantity");
	}

	public void setUnpassQuantity(java.math.BigDecimal unpassQuantity) {
		set("unpass_quantity", unpassQuantity);
	}
	
	public java.math.BigDecimal getUnpassQuantity() {
		return get("unpass_quantity");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	public void setInFrom(java.lang.String inFrom) {
		set("in_from", inFrom);
	}
	
	public java.lang.String getInFrom() {
		return getStr("in_from");
	}

	public void setInTime(java.util.Date inTime) {
		set("in_time", inTime);
	}
	
	public java.util.Date getInTime() {
		return get("in_time");
	}

	public void setCheckTime(java.util.Date checkTime) {
		set("check_time", checkTime);
	}
	
	public java.util.Date getCheckTime() {
		return get("check_time");
	}

	public void setCheckResult(java.lang.String checkResult) {
		set("check_result", checkResult);
	}
	
	public java.lang.String getCheckResult() {
		return getStr("check_result");
	}

}
