package com.chen.fy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFyBusinessInWarehouse<M extends BaseFyBusinessInWarehouse<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setInTime(java.util.Date inTime) {
		set("in_time", inTime);
	}
	
	public java.util.Date getInTime() {
		return get("in_time");
	}

	public void setRealInQuantity(java.math.BigDecimal realInQuantity) {
		set("real_in_quantity", realInQuantity);
	}
	
	public java.math.BigDecimal getRealInQuantity() {
		return get("real_in_quantity");
	}

	public void setInFrom(java.lang.String inFrom) {
		set("in_from", inFrom);
	}
	
	public java.lang.String getInFrom() {
		return getStr("in_from");
	}

	public void setIsCreateCheck(java.lang.Boolean isCreateCheck) {
		set("is_create_check", isCreateCheck);
	}
	
	public java.lang.Boolean getIsCreateCheck() {
		return get("is_create_check");
	}

	public void setCheckCreateTime(java.util.Date checkCreateTime) {
		set("check_create_time", checkCreateTime);
	}
	
	public java.util.Date getCheckCreateTime() {
		return get("check_create_time");
	}

	public void setCheckTime(java.util.Date checkTime) {
		set("check_time", checkTime);
	}
	
	public java.util.Date getCheckTime() {
		return get("check_time");
	}

	public void setCheckQuantity(java.math.BigDecimal checkQuantity) {
		set("check_quantity", checkQuantity);
	}
	
	public java.math.BigDecimal getCheckQuantity() {
		return get("check_quantity");
	}

	public void setCheckResult(java.lang.String checkResult) {
		set("check_result", checkResult);
	}
	
	public java.lang.String getCheckResult() {
		return getStr("check_result");
	}

	public void setCheckHandle(java.lang.String checkHandle) {
		set("check_handle", checkHandle);
	}
	
	public java.lang.String getCheckHandle() {
		return getStr("check_handle");
	}

	public void setIsCreateQuality(java.lang.Boolean isCreateQuality) {
		set("is_create_quality", isCreateQuality);
	}
	
	public java.lang.Boolean getIsCreateQuality() {
		return get("is_create_quality");
	}

	public void setIsCreateCanOut(java.lang.Boolean isCreateCanOut) {
		set("is_create_can_out", isCreateCanOut);
	}
	
	public java.lang.Boolean getIsCreateCanOut() {
		return get("is_create_can_out");
	}

	public void setCreateOutTime(java.util.Date createOutTime) {
		set("create_out_time", createOutTime);
	}
	
	public java.util.Date getCreateOutTime() {
		return get("create_out_time");
	}

	public void setIsCreatePay(java.lang.Boolean isCreatePay) {
		set("is_create_pay", isCreatePay);
	}
	
	public java.lang.Boolean getIsCreatePay() {
		return get("is_create_pay");
	}

	public void setPayCreateTime(java.util.Date payCreateTime) {
		set("pay_create_time", payCreateTime);
	}
	
	public java.util.Date getPayCreateTime() {
		return get("pay_create_time");
	}

	public void setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	public void setParentId(java.lang.Integer parentId) {
		set("parent_id", parentId);
	}
	
	public java.lang.Integer getParentId() {
		return getInt("parent_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setPayMonth(java.util.Date payMonth) {
		set("pay_month", payMonth);
	}
	
	public java.util.Date getPayMonth() {
		return get("pay_month");
	}

}
