package com.chen.fy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFyBusinessGetpay<M extends BaseFyBusinessGetpay<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setCategoryId(java.lang.Integer categoryId) {
		set("category_id", categoryId);
	}
	
	public java.lang.Integer getCategoryId() {
		return getInt("category_id");
	}

	public void setPlanerId(java.lang.Integer planerId) {
		set("planer_id", planerId);
	}
	
	public java.lang.Integer getPlanerId() {
		return getInt("planer_id");
	}

	public void setWorkOrderNo(java.lang.String workOrderNo) {
		set("work_order_no", workOrderNo);
	}
	
	public java.lang.String getWorkOrderNo() {
		return getStr("work_order_no");
	}

	public void setDeliveryNo(java.lang.String deliveryNo) {
		set("delivery_no", deliveryNo);
	}
	
	public java.lang.String getDeliveryNo() {
		return getStr("delivery_no");
	}

	public void setCommodityName(java.lang.String commodityName) {
		set("commodity_name", commodityName);
	}
	
	public java.lang.String getCommodityName() {
		return getStr("commodity_name");
	}

	public void setCommoditySpec(java.lang.String commoditySpec) {
		set("commodity_spec", commoditySpec);
	}
	
	public java.lang.String getCommoditySpec() {
		return getStr("commodity_spec");
	}

	public void setMapNo(java.lang.Integer mapNo) {
		set("map_no", mapNo);
	}
	
	public java.lang.Integer getMapNo() {
		return getInt("map_no");
	}

	public void setQuantity(java.lang.Integer quantity) {
		set("quantity", quantity);
	}
	
	public java.lang.Integer getQuantity() {
		return getInt("quantity");
	}

	public void setUnit(java.lang.Integer unit) {
		set("unit", unit);
	}
	
	public java.lang.Integer getUnit() {
		return getInt("unit");
	}

	public void setUntaxCost(java.math.BigDecimal untaxCost) {
		set("untax_cost", untaxCost);
	}
	
	public java.math.BigDecimal getUntaxCost() {
		return get("untax_cost");
	}

	public void setPayUnit(java.lang.Integer payUnit) {
		set("pay_unit", payUnit);
	}
	
	public java.lang.Integer getPayUnit() {
		return getInt("pay_unit");
	}

	public void setOutStoreTime(java.util.Date outStoreTime) {
		set("out_store_time", outStoreTime);
	}
	
	public java.util.Date getOutStoreTime() {
		return get("out_store_time");
	}

	public void setOutAquantity(java.lang.Integer outAquantity) {
		set("out_aquantity", outAquantity);
	}
	
	public java.lang.Integer getOutAquantity() {
		return getInt("out_aquantity");
	}

	public void setIsCreateBill(java.lang.Boolean isCreateBill) {
		set("is_create_bill", isCreateBill);
	}
	
	public java.lang.Boolean getIsCreateBill() {
		return get("is_create_bill");
	}

	public void setBillQuantity(java.lang.Integer billQuantity) {
		set("bill_quantity", billQuantity);
	}
	
	public java.lang.Integer getBillQuantity() {
		return getInt("bill_quantity");
	}

	public void setBillCreateTime(java.util.Date billCreateTime) {
		set("bill_create_time", billCreateTime);
	}
	
	public java.util.Date getBillCreateTime() {
		return get("bill_create_time");
	}

}
