package com.chen.fy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFyBusinessSumPaybill<M extends BaseFyBusinessSumPaybill<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setSupplier(java.lang.Integer supplier) {
		set("supplier", supplier);
	}
	
	public java.lang.Integer getSupplier() {
		return getInt("supplier");
	}

	public void setBillNo(java.lang.String billNo) {
		set("bill_no", billNo);
	}
	
	public java.lang.String getBillNo() {
		return getStr("bill_no");
	}

	public void setHangPeriod(java.lang.String hangPeriod) {
		set("hang_period", hangPeriod);
	}
	
	public java.lang.String getHangPeriod() {
		return getStr("hang_period");
	}

	public void setBillPeriod(java.lang.String billPeriod) {
		set("bill_period", billPeriod);
	}
	
	public java.lang.String getBillPeriod() {
		return getStr("bill_period");
	}

	public void setBillAccount(java.math.BigDecimal billAccount) {
		set("bill_account", billAccount);
	}
	
	public java.math.BigDecimal getBillAccount() {
		return get("bill_account");
	}

	public void setHadBillAccount(java.math.BigDecimal hadBillAccount) {
		set("had_bill_account", hadBillAccount);
	}
	
	public java.math.BigDecimal getHadBillAccount() {
		return get("had_bill_account");
	}

	public void setUnbillAccount(java.math.BigDecimal unbillAccount) {
		set("unbill_account", unbillAccount);
	}
	
	public java.math.BigDecimal getUnbillAccount() {
		return get("unbill_account");
	}

}
