package com.chen.fy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFyBusinessOutWarehouse<M extends BaseFyBusinessOutWarehouse<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setCategoryId(java.lang.Integer categoryId) {
		set("category_id", categoryId);
	}
	
	public java.lang.Integer getCategoryId() {
		return getInt("category_id");
	}

	public void setPlanerId(java.lang.Integer planerId) {
		set("planer_id", planerId);
	}
	
	public java.lang.Integer getPlanerId() {
		return getInt("planer_id");
	}

	public void setWorkBillNo(java.lang.String workBillNo) {
		set("work_bill_no", workBillNo);
	}
	
	public java.lang.String getWorkBillNo() {
		return getStr("work_bill_no");
	}

	public void setDeliveryNo(java.lang.String deliveryNo) {
		set("delivery_no", deliveryNo);
	}
	
	public java.lang.String getDeliveryNo() {
		return getStr("delivery_no");
	}

	public void setCommodityName(java.lang.String commodityName) {
		set("commodity_name", commodityName);
	}
	
	public java.lang.String getCommodityName() {
		return getStr("commodity_name");
	}

	public void setCommoditySpec(java.lang.String commoditySpec) {
		set("commodity_spec", commoditySpec);
	}
	
	public java.lang.String getCommoditySpec() {
		return getStr("commodity_spec");
	}

	public void setMapNo(java.lang.Integer mapNo) {
		set("map_no", mapNo);
	}
	
	public java.lang.Integer getMapNo() {
		return getInt("map_no");
	}

	public void setQuantity(java.lang.Integer quantity) {
		set("quantity", quantity);
	}
	
	public java.lang.Integer getQuantity() {
		return getInt("quantity");
	}

	public void setUnit(java.lang.Integer unit) {
		set("unit", unit);
	}
	
	public java.lang.Integer getUnit() {
		return getInt("unit");
	}

	public void setReceiveAddress(java.lang.String receiveAddress) {
		set("receive_address", receiveAddress);
	}
	
	public java.lang.String getReceiveAddress() {
		return getStr("receive_address");
	}

	public void setTransportType(java.lang.String transportType) {
		set("transport_type", transportType);
	}
	
	public java.lang.String getTransportType() {
		return getStr("transport_type");
	}

	public void setTransportCompany(java.lang.String transportCompany) {
		set("transport_company", transportCompany);
	}
	
	public java.lang.String getTransportCompany() {
		return getStr("transport_company");
	}

	public void setTransportFee(java.math.BigDecimal transportFee) {
		set("transport_fee", transportFee);
	}
	
	public java.math.BigDecimal getTransportFee() {
		return get("transport_fee");
	}

	public void setTransportWeight(java.lang.Double transportWeight) {
		set("transport_weight", transportWeight);
	}
	
	public java.lang.Double getTransportWeight() {
		return getDouble("transport_weight");
	}

	public void setTransportNo(java.lang.String transportNo) {
		set("transport_no", transportNo);
	}
	
	public java.lang.String getTransportNo() {
		return getStr("transport_no");
	}

	public void setIsCreateGetPay(java.lang.Boolean isCreateGetPay) {
		set("is_create_get_pay", isCreateGetPay);
	}
	
	public java.lang.Boolean getIsCreateGetPay() {
		return get("is_create_get_pay");
	}

	public void setOutTime(java.util.Date outTime) {
		set("out_time", outTime);
	}
	
	public java.util.Date getOutTime() {
		return get("out_time");
	}

	public void setOutQuantity(java.lang.Integer outQuantity) {
		set("out_quantity", outQuantity);
	}
	
	public java.lang.Integer getOutQuantity() {
		return getInt("out_quantity");
	}

	public void setIsBackPay(java.lang.Boolean isBackPay) {
		set("is_back_pay", isBackPay);
	}
	
	public java.lang.Boolean getIsBackPay() {
		return get("is_back_pay");
	}

	public void setBackReson(java.lang.String backReson) {
		set("back_reson", backReson);
	}
	
	public java.lang.String getBackReson() {
		return getStr("back_reson");
	}

	public void setIsCreateAfterSale(java.lang.Boolean isCreateAfterSale) {
		set("is_create_after_sale", isCreateAfterSale);
	}
	
	public java.lang.Boolean getIsCreateAfterSale() {
		return get("is_create_after_sale");
	}

	public void setAfterSaleCreateTime(java.util.Date afterSaleCreateTime) {
		set("after_sale_create_time", afterSaleCreateTime);
	}
	
	public java.util.Date getAfterSaleCreateTime() {
		return get("after_sale_create_time");
	}

}
