package com.chen.fy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFyPaySum<M extends BaseFyPaySum<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setHangAmount(java.math.BigDecimal hangAmount) {
		set("hang_amount", hangAmount);
	}
	
	public java.math.BigDecimal getHangAmount() {
		return get("hang_amount");
	}

	public void setHangQuantity(java.math.BigDecimal hangQuantity) {
		set("hang_quantity", hangQuantity);
	}
	
	public java.math.BigDecimal getHangQuantity() {
		return get("hang_quantity");
	}

	public void setUnhangQuantity(java.math.BigDecimal unhangQuantity) {
		set("unhang_quantity", unhangQuantity);
	}
	
	public java.math.BigDecimal getUnhangQuantity() {
		return get("unhang_quantity");
	}

	public void setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

}
