package com.chen.fy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFyBusinessInWarehouse<M extends BaseFyBusinessInWarehouse<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setInTime(java.util.Date inTime) {
		set("in_time", inTime);
	}
	
	public java.util.Date getInTime() {
		return get("in_time");
	}

	public void setInFrom(java.lang.String inFrom) {
		set("in_from", inFrom);
	}
	
	public java.lang.String getInFrom() {
		return getStr("in_from");
	}

	public void setCheckCreateTime(java.util.Date checkCreateTime) {
		set("check_create_time", checkCreateTime);
	}
	
	public java.util.Date getCheckCreateTime() {
		return get("check_create_time");
	}

	public void setCheckTime(java.util.Date checkTime) {
		set("check_time", checkTime);
	}
	
	public java.util.Date getCheckTime() {
		return get("check_time");
	}

	public void setCheckResult(java.lang.String checkResult) {
		set("check_result", checkResult);
	}
	
	public java.lang.String getCheckResult() {
		return getStr("check_result");
	}

	public void setCheckHandle(java.lang.String checkHandle) {
		set("check_handle", checkHandle);
	}
	
	public java.lang.String getCheckHandle() {
		return getStr("check_handle");
	}

	public void setIsCreateCanOut(java.lang.Boolean isCreateCanOut) {
		set("is_create_can_out", isCreateCanOut);
	}
	
	public java.lang.Boolean getIsCreateCanOut() {
		return get("is_create_can_out");
	}

	public void setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	public void setParentId(java.lang.Integer parentId) {
		set("parent_id", parentId);
	}
	
	public java.lang.Integer getParentId() {
		return getInt("parent_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setPayMonth(java.util.Date payMonth) {
		set("pay_month", payMonth);
	}
	
	public java.util.Date getPayMonth() {
		return get("pay_month");
	}

	public void setInQuantity(java.lang.Integer inQuantity) {
		set("in_quantity", inQuantity);
	}
	
	public java.lang.Integer getInQuantity() {
		return getInt("in_quantity");
	}

	public void setPassQuantity(java.lang.Integer passQuantity) {
		set("pass_quantity", passQuantity);
	}
	
	public java.lang.Integer getPassQuantity() {
		return getInt("pass_quantity");
	}

	public void setUnpassQuantity(java.lang.Integer unpassQuantity) {
		set("unpass_quantity", unpassQuantity);
	}
	
	public java.lang.Integer getUnpassQuantity() {
		return getInt("unpass_quantity");
	}

	public void setExceptionReson(java.lang.String exceptionReson) {
		set("exception_reson", exceptionReson);
	}
	
	public java.lang.String getExceptionReson() {
		return getStr("exception_reson");
	}

	public void setCheckRemark(java.lang.String checkRemark) {
		set("check_remark", checkRemark);
	}
	
	public java.lang.String getCheckRemark() {
		return getStr("check_remark");
	}

	public void setCreateBy(java.lang.Integer createBy) {
		set("create_by", createBy);
	}
	
	public java.lang.Integer getCreateBy() {
		return getInt("create_by");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setUpdateBy(java.lang.Integer updateBy) {
		set("update_by", updateBy);
	}
	
	public java.lang.Integer getUpdateBy() {
		return getInt("update_by");
	}

}
