package com.chen.fy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFyCheckCollect<M extends BaseFyCheckCollect<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setSupplierId(java.lang.Integer supplierId) {
		set("supplier_id", supplierId);
	}
	
	public java.lang.Integer getSupplierId() {
		return getInt("supplier_id");
	}

	public void setInhouseQuantity(java.lang.Integer inhouseQuantity) {
		set("inhouse_quantity", inhouseQuantity);
	}
	
	public java.lang.Integer getInhouseQuantity() {
		return getInt("inhouse_quantity");
	}

	public void setPassQuantity(java.lang.Integer passQuantity) {
		set("pass_quantity", passQuantity);
	}
	
	public java.lang.Integer getPassQuantity() {
		return getInt("pass_quantity");
	}

	public void setUnpassQuantity(java.lang.Integer unpassQuantity) {
		set("unpass_quantity", unpassQuantity);
	}
	
	public java.lang.Integer getUnpassQuantity() {
		return getInt("unpass_quantity");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
