package com.chen.fy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFyBusinessPurchase<M extends BaseFyBusinessPurchase<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setPurchaseNo(java.lang.String purchaseNo) {
		set("purchase_no", purchaseNo);
	}
	
	public java.lang.String getPurchaseNo() {
		return getStr("purchase_no");
	}

	public void setPurchaseDate(java.util.Date purchaseDate) {
		set("purchase_date", purchaseDate);
	}
	
	public java.util.Date getPurchaseDate() {
		return get("purchase_date");
	}

	public void setPurchaseSingleWeight(java.math.BigDecimal purchaseSingleWeight) {
		set("purchase_single_weight", purchaseSingleWeight);
	}
	
	public java.math.BigDecimal getPurchaseSingleWeight() {
		return get("purchase_single_weight");
	}

	public void setPurchaseWeight(java.math.BigDecimal purchaseWeight) {
		set("purchase_weight", purchaseWeight);
	}
	
	public java.math.BigDecimal getPurchaseWeight() {
		return get("purchase_weight");
	}

	public void setPurchaseCost(java.math.BigDecimal purchaseCost) {
		set("purchase_cost", purchaseCost);
	}
	
	public java.math.BigDecimal getPurchaseCost() {
		return get("purchase_cost");
	}

	public void setPurchaseAccount(java.math.BigDecimal purchaseAccount) {
		set("purchase_account", purchaseAccount);
	}
	
	public java.math.BigDecimal getPurchaseAccount() {
		return get("purchase_account");
	}

	public void setParentId(java.lang.Integer parentId) {
		set("parent_id", parentId);
	}
	
	public java.lang.Integer getParentId() {
		return getInt("parent_id");
	}

	public void setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	public void setSupplierId(java.lang.Integer supplierId) {
		set("supplier_id", supplierId);
	}
	
	public java.lang.Integer getSupplierId() {
		return getInt("supplier_id");
	}

	public void setDiscount(java.math.BigDecimal discount) {
		set("discount", discount);
	}
	
	public java.math.BigDecimal getDiscount() {
		return get("discount");
	}

	public void setDiscountAccount(java.math.BigDecimal discountAccount) {
		set("discount_account", discountAccount);
	}
	
	public java.math.BigDecimal getDiscountAccount() {
		return get("discount_account");
	}

	public void setPurchaseRemark(java.lang.String purchaseRemark) {
		set("purchase_remark", purchaseRemark);
	}
	
	public java.lang.String getPurchaseRemark() {
		return getStr("purchase_remark");
	}

	public void setCanDownload(java.lang.Boolean canDownload) {
		set("can_download", canDownload);
	}
	
	public java.lang.Boolean getCanDownload() {
		return get("can_download");
	}

	public void setHangStatus(java.lang.String hangStatus) {
		set("hang_status", hangStatus);
	}
	
	public java.lang.String getHangStatus() {
		return getStr("hang_status");
	}

	public void setUnhangQuantity(java.math.BigDecimal unhangQuantity) {
		set("unhang_quantity", unhangQuantity);
	}
	
	public java.math.BigDecimal getUnhangQuantity() {
		return get("unhang_quantity");
	}

	public void setHangQuantity(java.math.BigDecimal hangQuantity) {
		set("hang_quantity", hangQuantity);
	}
	
	public java.math.BigDecimal getHangQuantity() {
		return get("hang_quantity");
	}

	public void setPurchaseQuantity(java.math.BigDecimal purchaseQuantity) {
		set("purchase_quantity", purchaseQuantity);
	}
	
	public java.math.BigDecimal getPurchaseQuantity() {
		return get("purchase_quantity");
	}

	public void setPurchaseTitle(java.lang.String purchaseTitle) {
		set("purchase_title", purchaseTitle);
	}
	
	public java.lang.String getPurchaseTitle() {
		return getStr("purchase_title");
	}

}
