package com.chen.fy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFyCheckCollect<M extends BaseFyCheckCollect<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setSupplierId(java.lang.Integer supplierId) {
		set("supplier_id", supplierId);
	}
	
	public java.lang.Integer getSupplierId() {
		return getInt("supplier_id");
	}

	public void setInhouseQuantity(java.lang.Integer inhouseQuantity) {
		set("inhouse_quantity", inhouseQuantity);
	}
	
	public java.lang.Integer getInhouseQuantity() {
		return getInt("inhouse_quantity");
	}

	public void setPassQuantity(java.lang.Integer passQuantity) {
		set("pass_quantity", passQuantity);
	}
	
	public java.lang.Integer getPassQuantity() {
		return getInt("pass_quantity");
	}

	public void setUnpassQuantity(java.lang.Integer unpassQuantity) {
		set("unpass_quantity", unpassQuantity);
	}
	
	public java.lang.Integer getUnpassQuantity() {
		return getInt("unpass_quantity");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	public void setInFrom(java.lang.String inFrom) {
		set("in_from", inFrom);
	}
	
	public java.lang.String getInFrom() {
		return getStr("in_from");
	}

	public void setInTime(java.util.Date inTime) {
		set("in_time", inTime);
	}
	
	public java.util.Date getInTime() {
		return get("in_time");
	}

	public void setCheckTime(java.util.Date checkTime) {
		set("check_time", checkTime);
	}
	
	public java.util.Date getCheckTime() {
		return get("check_time");
	}

	public void setCheckResult(java.lang.String checkResult) {
		set("check_result", checkResult);
	}
	
	public java.lang.String getCheckResult() {
		return getStr("check_result");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCreateBy(java.lang.Integer createBy) {
		set("create_by", createBy);
	}
	
	public java.lang.Integer getCreateBy() {
		return getInt("create_by");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setUpdateBy(java.lang.Integer updateBy) {
		set("update_by", updateBy);
	}
	
	public java.lang.Integer getUpdateBy() {
		return getInt("update_by");
	}

}
