package com.chen.fy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseConfig<M extends BaseConfig<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setAcount(java.lang.Integer acount) {
		set("acount", acount);
	}
	
	public java.lang.Integer getAcount() {
		return getInt("acount");
	}

	public void setPageSize(java.lang.Integer pageSize) {
		set("page_size", pageSize);
	}
	
	public java.lang.Integer getPageSize() {
		return getInt("page_size");
	}

}
