package com.chen.fy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFyBusinessBill<M extends BaseFyBusinessBill<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setCategoryId(java.lang.Integer categoryId) {
		set("category_id", categoryId);
	}
	
	public java.lang.Integer getCategoryId() {
		return getInt("category_id");
	}

	public void setPlanerId(java.lang.Integer planerId) {
		set("planer_id", planerId);
	}
	
	public java.lang.Integer getPlanerId() {
		return getInt("planer_id");
	}

	public void setWorkOrderNo(java.lang.String workOrderNo) {
		set("work_order_no", workOrderNo);
	}
	
	public java.lang.String getWorkOrderNo() {
		return getStr("work_order_no");
	}

	public void setDeliveryNo(java.lang.String deliveryNo) {
		set("delivery_no", deliveryNo);
	}
	
	public java.lang.String getDeliveryNo() {
		return getStr("delivery_no");
	}

	public void setCommodityName(java.lang.String commodityName) {
		set("commodity_name", commodityName);
	}
	
	public java.lang.String getCommodityName() {
		return getStr("commodity_name");
	}

	public void setCommoditySpec(java.lang.String commoditySpec) {
		set("commodity_spec", commoditySpec);
	}
	
	public java.lang.String getCommoditySpec() {
		return getStr("commodity_spec");
	}

	public void setMapNo(java.lang.Integer mapNo) {
		set("map_no", mapNo);
	}
	
	public java.lang.Integer getMapNo() {
		return getInt("map_no");
	}

	public void setQuantity(java.lang.Integer quantity) {
		set("quantity", quantity);
	}
	
	public java.lang.Integer getQuantity() {
		return getInt("quantity");
	}

	public void setUnit(java.lang.Integer unit) {
		set("unit", unit);
	}
	
	public java.lang.Integer getUnit() {
		return getInt("unit");
	}

	public void setUntaxCost(java.math.BigDecimal untaxCost) {
		set("untax_cost", untaxCost);
	}
	
	public java.math.BigDecimal getUntaxCost() {
		return get("untax_cost");
	}

	public void setHangTime(java.util.Date hangTime) {
		set("hang_time", hangTime);
	}
	
	public java.util.Date getHangTime() {
		return get("hang_time");
	}

	public void setHangStatus(java.lang.String hangStatus) {
		set("hang_status", hangStatus);
	}
	
	public java.lang.String getHangStatus() {
		return getStr("hang_status");
	}

	public void setHangQuantity(java.lang.Integer hangQuantity) {
		set("hang_quantity", hangQuantity);
	}
	
	public java.lang.Integer getHangQuantity() {
		return getInt("hang_quantity");
	}

	public void setHangAmount(java.math.BigDecimal hangAmount) {
		set("hang_amount", hangAmount);
	}
	
	public java.math.BigDecimal getHangAmount() {
		return get("hang_amount");
	}

	public void setUnhangQuantity(java.lang.Integer unhangQuantity) {
		set("unhang_quantity", unhangQuantity);
	}
	
	public java.lang.Integer getUnhangQuantity() {
		return getInt("unhang_quantity");
	}

	public void setIsCreatePaybill(java.lang.Boolean isCreatePaybill) {
		set("is_create_paybill", isCreatePaybill);
	}
	
	public java.lang.Boolean getIsCreatePaybill() {
		return get("is_create_paybill");
	}

	public void setPaybillCreateTime(java.util.Date paybillCreateTime) {
		set("paybill_create_time", paybillCreateTime);
	}
	
	public java.util.Date getPaybillCreateTime() {
		return get("paybill_create_time");
	}

}
