package com.chen.fy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRoleCol<M extends BaseRoleCol<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setRoleId(java.lang.Integer roleId) {
		set("roleId", roleId);
	}
	
	public java.lang.Integer getRoleId() {
		return getInt("roleId");
	}

	public void setColName(java.lang.String colName) {
		set("col_name", colName);
	}
	
	public java.lang.String getColName() {
		return getStr("col_name");
	}

	public void setTableName(java.lang.String tableName) {
		set("table_name", tableName);
	}
	
	public java.lang.String getTableName() {
		return getStr("table_name");
	}

}
