package com.chen.fy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFyBusinessReady<M extends BaseFyBusinessReady<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setCustomer(java.lang.Integer customer) {
		set("customer", customer);
	}
	
	public java.lang.Integer getCustomer() {
		return getInt("customer");
	}

	public void setCategoryId(java.lang.Integer categoryId) {
		set("category_id", categoryId);
	}
	
	public java.lang.Integer getCategoryId() {
		return getInt("category_id");
	}

	public void setPlanerId(java.lang.Integer planerId) {
		set("planer_id", planerId);
	}
	
	public java.lang.Integer getPlanerId() {
		return getInt("planer_id");
	}

	public void setExecuStatus(java.lang.String execuStatus) {
		set("execu_status", execuStatus);
	}
	
	public java.lang.String getExecuStatus() {
		return getStr("execu_status");
	}

	public void setUrgentStatus(java.lang.String urgentStatus) {
		set("urgent_status", urgentStatus);
	}
	
	public java.lang.String getUrgentStatus() {
		return getStr("urgent_status");
	}

	public void setImportTime(java.util.Date importTime) {
		set("import_time", importTime);
	}
	
	public java.util.Date getImportTime() {
		return get("import_time");
	}

	public void setOrderDate(java.util.Date orderDate) {
		set("order_date", orderDate);
	}
	
	public java.util.Date getOrderDate() {
		return get("order_date");
	}

	public void setDeliveryDate(java.util.Date deliveryDate) {
		set("delivery_date", deliveryDate);
	}
	
	public java.util.Date getDeliveryDate() {
		return get("delivery_date");
	}

	public void setWorkOrderNo(java.lang.String workOrderNo) {
		set("work_order_no", workOrderNo);
	}
	
	public java.lang.String getWorkOrderNo() {
		return getStr("work_order_no");
	}

	public void setDeliveryNo(java.lang.String deliveryNo) {
		set("delivery_no", deliveryNo);
	}
	
	public java.lang.String getDeliveryNo() {
		return getStr("delivery_no");
	}

	public void setCommodityName(java.lang.String commodityName) {
		set("commodity_name", commodityName);
	}
	
	public java.lang.String getCommodityName() {
		return getStr("commodity_name");
	}

	public void setCommoditySpec(java.lang.String commoditySpec) {
		set("commodity_spec", commoditySpec);
	}
	
	public java.lang.String getCommoditySpec() {
		return getStr("commodity_spec");
	}

	public void setMapNo(java.lang.String mapNo) {
		set("map_no", mapNo);
	}
	
	public java.lang.String getMapNo() {
		return getStr("map_no");
	}

	public void setTechnology(java.lang.String technology) {
		set("technology", technology);
	}
	
	public java.lang.String getTechnology() {
		return getStr("technology");
	}

	public void setMachiningRequire(java.lang.String machiningRequire) {
		set("machining_require", machiningRequire);
	}
	
	public java.lang.String getMachiningRequire() {
		return getStr("machining_require");
	}

	public void setQuantity(java.math.BigDecimal quantity) {
		set("quantity", quantity);
	}
	
	public java.math.BigDecimal getQuantity() {
		return get("quantity");
	}

	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}
	
	public java.lang.String getUnit() {
		return getStr("unit");
	}

	public void setUntaxedCost(java.math.BigDecimal untaxedCost) {
		set("untaxed_cost", untaxedCost);
	}
	
	public java.math.BigDecimal getUntaxedCost() {
		return get("untaxed_cost");
	}

	public void setAddStatus(java.lang.String addStatus) {
		set("add_status", addStatus);
	}
	
	public java.lang.String getAddStatus() {
		return getStr("add_status");
	}

	public void setSupplierId(java.lang.Integer supplierId) {
		set("supplier_id", supplierId);
	}
	
	public java.lang.Integer getSupplierId() {
		return getInt("supplier_id");
	}

	public void setOrderNo(java.lang.String orderNo) {
		set("order_no", orderNo);
	}
	
	public java.lang.String getOrderNo() {
		return getStr("order_no");
	}

	public void setPurchaseQuanity(java.math.BigDecimal purchaseQuanity) {
		set("purchase_quanity", purchaseQuanity);
	}
	
	public java.math.BigDecimal getPurchaseQuanity() {
		return get("purchase_quanity");
	}

	public void setPurchaseUnit(java.lang.String purchaseUnit) {
		set("purchase_unit", purchaseUnit);
	}
	
	public java.lang.String getPurchaseUnit() {
		return getStr("purchase_unit");
	}

	public void setCost(java.math.BigDecimal cost) {
		set("cost", cost);
	}
	
	public java.math.BigDecimal getCost() {
		return get("cost");
	}

	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}
	
	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

	public void setDiscount(java.math.BigDecimal discount) {
		set("discount", discount);
	}
	
	public java.math.BigDecimal getDiscount() {
		return get("discount");
	}

	public void setDiscountAmount(java.math.BigDecimal discountAmount) {
		set("discount_amount", discountAmount);
	}
	
	public java.math.BigDecimal getDiscountAmount() {
		return get("discount_amount");
	}

	public void setCheckTime(java.util.Date checkTime) {
		set("check_time", checkTime);
	}
	
	public java.util.Date getCheckTime() {
		return get("check_time");
	}

	public void setCheckResult(java.lang.String checkResult) {
		set("check_result", checkResult);
	}
	
	public java.lang.String getCheckResult() {
		return getStr("check_result");
	}

	public void setHangQuantity(java.math.BigDecimal hangQuantity) {
		set("hang_quantity", hangQuantity);
	}
	
	public java.math.BigDecimal getHangQuantity() {
		return get("hang_quantity");
	}

	public void setHangAccount(java.math.BigDecimal hangAccount) {
		set("hang_account", hangAccount);
	}
	
	public java.math.BigDecimal getHangAccount() {
		return get("hang_account");
	}

	public void setHangDate(java.util.Date hangDate) {
		set("hang_date", hangDate);
	}
	
	public java.util.Date getHangDate() {
		return get("hang_date");
	}

	public void setIsProduct(java.lang.Boolean isProduct) {
		set("is_product", isProduct);
	}
	
	public java.lang.Boolean getIsProduct() {
		return get("is_product");
	}

	public void setOutDate1(java.util.Date outDate1) {
		set("out_date1", outDate1);
	}
	
	public java.util.Date getOutDate1() {
		return get("out_date1");
	}

	public void setOutQuantity1(java.math.BigDecimal outQuantity1) {
		set("out_quantity1", outQuantity1);
	}
	
	public java.math.BigDecimal getOutQuantity1() {
		return get("out_quantity1");
	}

	public void setInQuantity1(java.math.BigDecimal inQuantity1) {
		set("in_quantity1", inQuantity1);
	}
	
	public java.math.BigDecimal getInQuantity1() {
		return get("in_quantity1");
	}

	public void setInDate1(java.util.Date inDate1) {
		set("in_date1", inDate1);
	}
	
	public java.util.Date getInDate1() {
		return get("in_date1");
	}

	public void setOutDate2(java.util.Date outDate2) {
		set("out_date2", outDate2);
	}
	
	public java.util.Date getOutDate2() {
		return get("out_date2");
	}

	public void setOutQuantity2(java.math.BigDecimal outQuantity2) {
		set("out_quantity2", outQuantity2);
	}
	
	public java.math.BigDecimal getOutQuantity2() {
		return get("out_quantity2");
	}

	public void setInQuantity2(java.math.BigDecimal inQuantity2) {
		set("in_quantity2", inQuantity2);
	}
	
	public java.math.BigDecimal getInQuantity2() {
		return get("in_quantity2");
	}

	public void setInDate2(java.util.Date inDate2) {
		set("in_date2", inDate2);
	}
	
	public java.util.Date getInDate2() {
		return get("in_date2");
	}

	public void setOutDate3(java.util.Date outDate3) {
		set("out_date3", outDate3);
	}
	
	public java.util.Date getOutDate3() {
		return get("out_date3");
	}

	public void setOutQuantity3(java.math.BigDecimal outQuantity3) {
		set("out_quantity3", outQuantity3);
	}
	
	public java.math.BigDecimal getOutQuantity3() {
		return get("out_quantity3");
	}

	public void setInQuantity3(java.math.BigDecimal inQuantity3) {
		set("in_quantity3", inQuantity3);
	}
	
	public java.math.BigDecimal getInQuantity3() {
		return get("in_quantity3");
	}

	public void setInDate3(java.util.Date inDate3) {
		set("in_date3", inDate3);
	}
	
	public java.util.Date getInDate3() {
		return get("in_date3");
	}

	public void setOutDate4(java.util.Date outDate4) {
		set("out_date4", outDate4);
	}
	
	public java.util.Date getOutDate4() {
		return get("out_date4");
	}

	public void setOutQuantity4(java.math.BigDecimal outQuantity4) {
		set("out_quantity4", outQuantity4);
	}
	
	public java.math.BigDecimal getOutQuantity4() {
		return get("out_quantity4");
	}

	public void setInQuantity4(java.math.BigDecimal inQuantity4) {
		set("in_quantity4", inQuantity4);
	}
	
	public java.math.BigDecimal getInQuantity4() {
		return get("in_quantity4");
	}

	public void setInDate4(java.util.Date inDate4) {
		set("in_date4", inDate4);
	}
	
	public java.util.Date getInDate4() {
		return get("in_date4");
	}

	public void setOutDate5(java.util.Date outDate5) {
		set("out_date5", outDate5);
	}
	
	public java.util.Date getOutDate5() {
		return get("out_date5");
	}

	public void setOutQuantity5(java.math.BigDecimal outQuantity5) {
		set("out_quantity5", outQuantity5);
	}
	
	public java.math.BigDecimal getOutQuantity5() {
		return get("out_quantity5");
	}

	public void setInQuantity5(java.math.BigDecimal inQuantity5) {
		set("in_quantity5", inQuantity5);
	}
	
	public java.math.BigDecimal getInQuantity5() {
		return get("in_quantity5");
	}

	public void setInDate5(java.util.Date inDate5) {
		set("in_date5", inDate5);
	}
	
	public java.util.Date getInDate5() {
		return get("in_date5");
	}

}
