package com.chen.fy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePerson<M extends BasePerson<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setNativePlace(java.lang.String nativePlace) {
		set("native_place", nativePlace);
	}
	
	public java.lang.String getNativePlace() {
		return getStr("native_place");
	}

	public void setSex(java.lang.Boolean sex) {
		set("sex", sex);
	}
	
	public java.lang.Boolean getSex() {
		return get("sex");
	}

	public void setBirthDate(java.util.Date birthDate) {
		set("birth_date", birthDate);
	}
	
	public java.util.Date getBirthDate() {
		return get("birth_date");
	}

	public void setEntryDate(java.util.Date entryDate) {
		set("entry_date", entryDate);
	}
	
	public java.util.Date getEntryDate() {
		return get("entry_date");
	}

	public void setQuitDate(java.util.Date quitDate) {
		set("quit_date", quitDate);
	}
	
	public java.util.Date getQuitDate() {
		return get("quit_date");
	}

	public void setContactType(java.lang.String contactType) {
		set("contact_type", contactType);
	}
	
	public java.lang.String getContactType() {
		return getStr("contact_type");
	}

	public void setEducation(java.lang.String education) {
		set("education", education);
	}
	
	public java.lang.String getEducation() {
		return getStr("education");
	}

	public void setPoliticalStatus(java.lang.String politicalStatus) {
		set("political_status", politicalStatus);
	}
	
	public java.lang.String getPoliticalStatus() {
		return getStr("political_status");
	}

	public void setAccommodation(java.lang.String accommodation) {
		set("accommodation", accommodation);
	}
	
	public java.lang.String getAccommodation() {
		return getStr("accommodation");
	}

	public void setPost(java.lang.String post) {
		set("post", post);
	}
	
	public java.lang.String getPost() {
		return getStr("post");
	}

	public void setDepartmentId(java.lang.Integer departmentId) {
		set("department_id", departmentId);
	}
	
	public java.lang.Integer getDepartmentId() {
		return getInt("department_id");
	}

	public void setJobStatus(java.lang.String jobStatus) {
		set("job_status", jobStatus);
	}
	
	public java.lang.String getJobStatus() {
		return getStr("job_status");
	}

	public void setExecBaseSalary(java.math.BigDecimal execBaseSalary) {
		set("exec_base_salary", execBaseSalary);
	}
	
	public java.math.BigDecimal getExecBaseSalary() {
		return get("exec_base_salary");
	}

	public void setAdjustBaseSalary1(java.math.BigDecimal adjustBaseSalary1) {
		set("adjust_base_salary1", adjustBaseSalary1);
	}
	
	public java.math.BigDecimal getAdjustBaseSalary1() {
		return get("adjust_base_salary1");
	}

	public void setAdjustBaseSalary2(java.math.BigDecimal adjustBaseSalary2) {
		set("adjust_base_salary2", adjustBaseSalary2);
	}
	
	public java.math.BigDecimal getAdjustBaseSalary2() {
		return get("adjust_base_salary2");
	}

	public void setAdjustBaseSalary3(java.math.BigDecimal adjustBaseSalary3) {
		set("adjust_base_salary3", adjustBaseSalary3);
	}
	
	public java.math.BigDecimal getAdjustBaseSalary3() {
		return get("adjust_base_salary3");
	}

	public void setAdjustBaseSalary4(java.math.BigDecimal adjustBaseSalary4) {
		set("adjust_base_salary4", adjustBaseSalary4);
	}
	
	public java.math.BigDecimal getAdjustBaseSalary4() {
		return get("adjust_base_salary4");
	}

	public void setAdjustBaseSalary5(java.math.BigDecimal adjustBaseSalary5) {
		set("adjust_base_salary5", adjustBaseSalary5);
	}
	
	public java.math.BigDecimal getAdjustBaseSalary5() {
		return get("adjust_base_salary5");
	}

}
