package com.chen.fy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFyComplaint<M extends BaseFyComplaint<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setCustomerName(java.lang.Integer customerName) {
		set("customer_name", customerName);
	}
	
	public java.lang.Integer getCustomerName() {
		return getInt("customer_name");
	}

	public void setComplaintDate(java.util.Date complaintDate) {
		set("complaint_date", complaintDate);
	}
	
	public java.util.Date getComplaintDate() {
		return get("complaint_date");
	}

	public void setMapNo(java.lang.String mapNo) {
		set("map_no", mapNo);
	}
	
	public java.lang.String getMapNo() {
		return getStr("map_no");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setQuantity(java.lang.Integer quantity) {
		set("quantity", quantity);
	}
	
	public java.lang.Integer getQuantity() {
		return getInt("quantity");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public void setHandleMethod(java.lang.String handleMethod) {
		set("handle_method", handleMethod);
	}
	
	public java.lang.String getHandleMethod() {
		return getStr("handle_method");
	}

	public void setSolution(java.lang.String solution) {
		set("solution", solution);
	}
	
	public java.lang.String getSolution() {
		return getStr("solution");
	}

	public void setDutyPart(java.lang.Integer dutyPart) {
		set("duty_part", dutyPart);
	}
	
	public java.lang.Integer getDutyPart() {
		return getInt("duty_part");
	}

	public void setDutyPerson(java.lang.Integer dutyPerson) {
		set("duty_person", dutyPerson);
	}
	
	public java.lang.Integer getDutyPerson() {
		return getInt("duty_person");
	}

	public void setRecordPart(java.lang.Integer recordPart) {
		set("record_part", recordPart);
	}
	
	public java.lang.Integer getRecordPart() {
		return getInt("record_part");
	}

	public void setRecordPerson(java.lang.Integer recordPerson) {
		set("record_person", recordPerson);
	}
	
	public java.lang.Integer getRecordPerson() {
		return getInt("record_person");
	}

	public void setHandleNo(java.lang.String handleNo) {
		set("handle_no", handleNo);
	}
	
	public java.lang.String getHandleNo() {
		return getStr("handle_no");
	}

}
