package com.chen.fy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFyBusinessProduce<M extends BaseFyBusinessProduce<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setIsCreatePlan(java.lang.Boolean isCreatePlan) {
		set("is_create_plan", isCreatePlan);
	}
	
	public java.lang.Boolean getIsCreatePlan() {
		return get("is_create_plan");
	}

	public void setHandleStatus(java.lang.String handleStatus) {
		set("handle_status", handleStatus);
	}
	
	public java.lang.String getHandleStatus() {
		return getStr("handle_status");
	}

	public void setPlanTime(java.util.Date planTime) {
		set("plan_time", planTime);
	}
	
	public java.util.Date getPlanTime() {
		return get("plan_time");
	}

	public void setPlanFinshTime(java.util.Date planFinshTime) {
		set("plan_finsh_time", planFinshTime);
	}
	
	public java.util.Date getPlanFinshTime() {
		return get("plan_finsh_time");
	}

	public void setPlanRemark(java.lang.String planRemark) {
		set("plan_remark", planRemark);
	}
	
	public java.lang.String getPlanRemark() {
		return getStr("plan_remark");
	}

	public void setInWarehouseTime(java.util.Date inWarehouseTime) {
		set("in_warehouse_time", inWarehouseTime);
	}
	
	public java.util.Date getInWarehouseTime() {
		return get("in_warehouse_time");
	}

	public void setParentId(java.lang.Integer parentId) {
		set("parent_id", parentId);
	}
	
	public java.lang.Integer getParentId() {
		return getInt("parent_id");
	}

	public void setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	public void setFinishTime(java.util.Date finishTime) {
		set("finish_time", finishTime);
	}
	
	public java.util.Date getFinishTime() {
		return get("finish_time");
	}

	public void setIsCreateInHouse(java.lang.Boolean isCreateInHouse) {
		set("is_create_in_house", isCreateInHouse);
	}
	
	public java.lang.Boolean getIsCreateInHouse() {
		return get("is_create_in_house");
	}

	public void setIsBackBack(java.lang.Boolean isBackBack) {
		set("is_back_back", isBackBack);
	}
	
	public java.lang.Boolean getIsBackBack() {
		return get("is_back_back");
	}

}
