package com.chen.fy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFyBusinessOutWarehouse<M extends BaseFyBusinessOutWarehouse<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setReceiveAddress(java.lang.String receiveAddress) {
		set("receive_address", receiveAddress);
	}
	
	public java.lang.String getReceiveAddress() {
		return getStr("receive_address");
	}

	public void setTransportType(java.lang.String transportType) {
		set("transport_type", transportType);
	}
	
	public java.lang.String getTransportType() {
		return getStr("transport_type");
	}

	public void setTransportCompany(java.lang.String transportCompany) {
		set("transport_company", transportCompany);
	}
	
	public java.lang.String getTransportCompany() {
		return getStr("transport_company");
	}

	public void setTransportFee(java.math.BigDecimal transportFee) {
		set("transport_fee", transportFee);
	}
	
	public java.math.BigDecimal getTransportFee() {
		return get("transport_fee");
	}

	public void setTransportWeight(java.lang.Double transportWeight) {
		set("transport_weight", transportWeight);
	}
	
	public java.lang.Double getTransportWeight() {
		return getDouble("transport_weight");
	}

	public void setTransportNo(java.lang.String transportNo) {
		set("transport_no", transportNo);
	}
	
	public java.lang.String getTransportNo() {
		return getStr("transport_no");
	}

	public void setOutTime(java.util.Date outTime) {
		set("out_time", outTime);
	}
	
	public java.util.Date getOutTime() {
		return get("out_time");
	}

	public void setOutQuantity(java.lang.Integer outQuantity) {
		set("out_quantity", outQuantity);
	}
	
	public java.lang.Integer getOutQuantity() {
		return getInt("out_quantity");
	}

	public void setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	public void setParentId(java.lang.Integer parentId) {
		set("parent_id", parentId);
	}
	
	public java.lang.Integer getParentId() {
		return getInt("parent_id");
	}

	public void setIsDownload(java.lang.Boolean isDownload) {
		set("is_download", isDownload);
	}
	
	public java.lang.Boolean getIsDownload() {
		return get("is_download");
	}

	public void setOutStatus(java.lang.Integer outStatus) {
		set("out_status", outStatus);
	}
	
	public java.lang.Integer getOutStatus() {
		return getInt("out_status");
	}

	public void setOutRemark(java.lang.String outRemark) {
		set("out_remark", outRemark);
	}
	
	public java.lang.String getOutRemark() {
		return getStr("out_remark");
	}

}
