package com.jfinal.club.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFyBaseFyfile<M extends BaseFyBaseFyfile<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setFilename(java.lang.String filename) {
		set("filename", filename);
	}
	
	public java.lang.String getFilename() {
		return getStr("filename");
	}

	public void setOriginalFileName(java.lang.String originalFileName) {
		set("originalFileName", originalFileName);
	}
	
	public java.lang.String getOriginalFileName() {
		return getStr("originalFileName");
	}

	public void setFilepath(java.lang.String filepath) {
		set("filepath", filepath);
	}
	
	public java.lang.String getFilepath() {
		return getStr("filepath");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCreateBy(java.lang.Integer createBy) {
		set("create_by", createBy);
	}
	
	public java.lang.Integer getCreateBy() {
		return getInt("create_by");
	}

	public void setFileSize(java.lang.Integer fileSize) {
		set("file_size", fileSize);
	}
	
	public java.lang.Integer getFileSize() {
		return getInt("file_size");
	}

}
