package com.jfinal.club.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFyBaseTaxRate<M extends BaseFyBaseTaxRate<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setTaxRate(java.lang.String taxRate) {
		set("tax_rate", taxRate);
	}
	
	public java.lang.String getTaxRate() {
		return getStr("tax_rate");
	}

	public void setMatchValue(java.math.BigDecimal matchValue) {
		set("match_value", matchValue);
	}
	
	public java.math.BigDecimal getMatchValue() {
		return get("match_value");
	}

}
