package com.chen.fy.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("fy_base_customer", "id", Customer.class);
		arp.addMapping("fy_base_department", "id", Department.class);
		arp.addMapping("fy_base_person", "id", Person.class);
		arp.addMapping("fy_base_supplier", "id", Supplier.class);
		arp.addMapping("fy_base_tax_rate", "id", TaxRate.class);
		arp.addMapping("fy_base_unit", "id", Unit.class);
		arp.addMapping("task_run_log", "id", TaskRunLog.class);
	}
}

