package com.chen.fy.model;

import com.chen.fy.model.base.BaseCategory;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Category extends BaseCategory<Category> {
	public final static Category dao = new Category().dao();

	public Page<Category> paginate(int i, int j, String string) {
		// TODO Auto-generated method stub
		return null;
	}
}
