package com.chen.fy.model;

import com.chen.fy.model.base.BaseCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Category extends BaseCategory<Category> {
	public final static Category dao = new Category().dao();
}
