package com.chen.fy.model;

import com.chen.fy.model.base.BaseColPermision;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ColPermision extends BaseColPermision<ColPermision> {
	public final static ColPermision dao = new ColPermision().dao();
}
