package com.chen.fy.model;

import com.chen.fy.model.base.BaseColumnPermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ColumnPermission extends BaseColumnPermission<ColumnPermission> {
	
}
