package com.chen.fy.model;

import com.chen.fy.model.base.BaseCustomer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Customer extends BaseCustomer<Customer> {
	public final static Customer dao = new Customer().dao();
	
}
