package com.chen.fy.model;

import com.chen.fy.model.base.BaseDepartment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Department extends BaseDepartment<Department> {
	public static final Department dao = new  Department().dao();
	
	public String getDutyName() {
		return getStr("dutyName");
	}
}
