package com.chen.fy.model;

import com.chen.fy.model.base.BaseFyAdvisoryCost;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FyAdvisoryCost extends BaseFyAdvisoryCost<FyAdvisoryCost> {
	public static final FyAdvisoryCost dao = new FyAdvisoryCost().dao();
}
