package com.chen.fy.model;

import com.chen.fy.model.base.BaseFyBizWwReceive;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FyBizWwReceive extends BaseFyBizWwReceive<FyBizWwReceive> {
	public static final FyBizWwReceive dao = new FyBizWwReceive().dao();
}
