package com.chen.fy.model;

import com.chen.fy.model.base.BaseFyBusinessInWarehouse;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FyBusinessInWarehouse extends BaseFyBusinessInWarehouse<FyBusinessInWarehouse> {
	public final static FyBusinessInWarehouse dao = new FyBusinessInWarehouse().dao();
}
