package com.chen.fy.model;

import com.chen.fy.model.base.BaseFyBusinessPaybill;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FyBusinessPaybill extends BaseFyBusinessPaybill<FyBusinessPaybill> {
	public final static FyBusinessPaybill dao = new FyBusinessPaybill().dao();
}
