package com.chen.fy.model;

import com.chen.fy.model.base.BaseFyBusinessDistribute;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FyBusinessDistribute extends BaseFyBusinessDistribute<FyBusinessDistribute> {
	public final static FyBusinessDistribute dao = new FyBusinessDistribute();

}
