package com.chen.fy.model;

import com.chen.fy.model.base.BaseFyBusinessReady;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FyBusinessReady extends BaseFyBusinessReady<FyBusinessReady> {

	public static FyBusinessReady dao=new FyBusinessReady().dao();
	
}
