package com.chen.fy.model;

import com.chen.fy.model.base.BaseFyBusinessReady;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FyBusinessReady extends BaseFyBusinessReady<FyBusinessReady> {

	public final static FyBusinessReady dao = new FyBusinessReady().dao();

	public String getCustomerName() {
		return getStr("customer_name");
	}
}
