package com.chen.fy.model;

import com.chen.fy.model.base.BaseFyBusinessAssist;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FyBusinessAssist extends BaseFyBusinessAssist<FyBusinessAssist> {
	public static final FyBusinessAssist dao = new FyBusinessAssist().dao();
}
