package com.chen.fy.model;

import com.chen.fy.model.base.BaseFyBusinessWarehouse;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FyBusinessWarehouse extends BaseFyBusinessWarehouse<FyBusinessWarehouse> {
	public static final FyBusinessWarehouse dao = new FyBusinessWarehouse().dao();
}
