package com.chen.fy.model;

import com.chen.fy.model.base.BaseFyBusinessOrderDelete;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FyBusinessOrderDelete extends BaseFyBusinessOrderDelete<FyBusinessOrderDelete> {
	
}
