package com.chen.fy.model;

import com.chen.fy.model.base.BaseFyBusinessGetpay;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FyBusinessGetpay extends BaseFyBusinessGetpay<FyBusinessGetpay> {
	public final static FyBusinessGetpay dao = new FyBusinessGetpay().dao();
}
