package com.chen.fy.model;

import com.chen.fy.model.base.BaseFyBusinessGetpaybill;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FyBusinessGetpaybill extends BaseFyBusinessGetpaybill<FyBusinessGetpaybill> {
	public final static FyBusinessGetpaybill dao = new FyBusinessGetpaybill().dao();
}
