package com.chen.fy.model;

import com.chen.fy.model.base.BaseFyBusinessSumPaybill;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FyBusinessSumPaybill extends BaseFyBusinessSumPaybill<FyBusinessSumPaybill> {
	public final static FyBusinessSumPaybill dao = new FyBusinessSumPaybill().dao();
}
