package com.chen.fy.model;

import com.chen.fy.model.base.BaseFyBusinessPurchase;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FyBusinessPurchase extends BaseFyBusinessPurchase<FyBusinessPurchase> {
	public final static FyBusinessPurchase dao = new FyBusinessPurchase().dao();
}
