package com.chen.fy.model;

import com.chen.fy.model.base.BaseFyBusinessOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FyBusinessOrder extends BaseFyBusinessOrder<FyBusinessOrder> {
	public final static FyBusinessOrder dao = new FyBusinessOrder().dao();
}
