package com.chen.fy.model;

import com.chen.fy.model.base.BaseFyBusinessOutWarehouse;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FyBusinessOutWarehouse extends BaseFyBusinessOutWarehouse<FyBusinessOutWarehouse> {
	public static final FyBusinessOutWarehouse dao = new FyBusinessOutWarehouse().dao();
}
