package com.chen.fy.model;

import com.chen.fy.model.base.BaseFyBusinessPurchaseCallback;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FyBusinessPurchaseCallback extends BaseFyBusinessPurchaseCallback<FyBusinessPurchaseCallback> {
	
}
