package com.chen.fy.model;

import com.chen.fy.model.base.BaseFyBusinessBill;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FyBusinessBill extends BaseFyBusinessBill<FyBusinessBill> {
	public static final FyBusinessBill dao = new FyBusinessBill().dao();
}
