package com.chen.fy.model;

import com.chen.fy.model.base.BaseFyBusinessProduce;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FyBusinessProduce extends BaseFyBusinessProduce<FyBusinessProduce> {
	public final static FyBusinessProduce dao = new FyBusinessProduce().dao();
}
