package com.chen.fy.model;

import com.chen.fy.model.base.BaseFyBusinessPay;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FyBusinessPay extends BaseFyBusinessPay<FyBusinessPay> {
	public final static FyBusinessPay dao = new FyBusinessPay().dao();
}
