package com.chen.fy.model;

import com.chen.fy.model.base.BaseFyCheckCollect;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FyCheckCollect extends BaseFyCheckCollect<FyCheckCollect> {
	
}
