package com.chen.fy.model;

import com.chen.fy.model.base.BaseFyComplaint;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FyComplaint extends BaseFyComplaint<FyComplaint> {
	public final static FyComplaint dao = new FyComplaint().dao();
}
