package com.chen.fy.model;

import com.chen.fy.model.base.BaseFyExceptionRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FyExceptionRecord extends BaseFyExceptionRecord<FyExceptionRecord> {
	
}
