package com.chen.fy.model;

import com.chen.fy.model.base.BaseFyfile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Fyfile extends BaseFyfile<Fyfile> {
	public final static Fyfile dao = new Fyfile().dao();
}
