package com.chen.fy.model;

import com.chen.fy.model.base.BaseFyPurchaseAudit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FyPurchaseAudit extends BaseFyPurchaseAudit<FyPurchaseAudit> {
	
}
