package com.chen.fy.model;

import com.chen.fy.model.base.BaseFyReadyPurchase;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FyReadyPurchase extends BaseFyReadyPurchase<FyReadyPurchase> {
	public final static FyReadyPurchase dao = new FyReadyPurchase().dao();
}
