package com.chen.fy.model;

import com.chen.fy.model.base.BaseFyReadyAdd;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FyReadyAdd extends BaseFyReadyAdd<FyReadyAdd> {
	public static final FyReadyAdd dao = new FyReadyAdd();
}
