package com.chen.fy.model;

import com.chen.fy.model.base.BaseFySupplierCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FySupplierCategory extends BaseFySupplierCategory<FySupplierCategory> {
	public final static FySupplierCategory dao = new FySupplierCategory().dao();

}
