package com.chen.fy.model;

import com.chen.fy.model.base.BaseFyUploadGetpay;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FyUploadGetpay extends BaseFyUploadGetpay<FyUploadGetpay> {
	public final static FyUploadGetpay dao = new FyUploadGetpay().dao();
}
