package com.chen.fy.model;

import com.chen.fy.model.base.BaseOrderUploadLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderUploadLog extends BaseOrderUploadLog<OrderUploadLog> {
	
}
