package com.chen.fy.model;

import com.chen.fy.model.base.BasePermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Permission extends BasePermission<Permission> {
	public final static Permission dao = new Permission().dao();
}
