package com.chen.fy.model;

import com.chen.fy.model.base.BasePerson;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Person extends BasePerson<Person> {
	public final static Person dao = new Person().dao();

}
