package com.chen.fy.model;

import com.chen.fy.model.base.BaseRolePermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RolePermission extends BaseRolePermission<RolePermission> {
	
}
