package com.chen.fy.model;

import com.chen.fy.model.base.BaseRoleCol;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleCol extends BaseRoleCol<RoleCol> {
	public final static RoleCol dao = new RoleCol().dao();
}
