package com.chen.fy.model;

import com.chen.fy.model.base.BaseTaskRunLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TaskRunLog extends BaseTaskRunLog<TaskRunLog> {
	
}
