package com.chen.fy.model;

import com.chen.fy.model.base.BaseUnit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Unit extends BaseUnit<Unit> {
	public static final Unit dao = new Unit().dao();
}
